//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.14 at 03:45:29 PM EDT 
//

package configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Environment">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TestDataFolderPath" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="TestResultsFolderPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ScreenShotFolderPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ScreenShotCapture" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CapturePageTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DebugMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DataXmlFileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SaveToXmlDataFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Database">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="encrypted_password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="connection_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "environment" })
@XmlRootElement(name = "TestingCoE")
public class TestingCoE {

	@XmlElement(name = "Environment", required = true)
	protected TestingCoE.Environment environment;

	/**
	 * Gets the value of the environment property.
	 * 
	 * @return possible object is {@link TestingCoE.Environment }
	 * 
	 */
	public TestingCoE.Environment getEnvironment() {
		return environment;
	}

	/**
	 * Sets the value of the environment property.
	 * 
	 * @param value
	 *            allowed object is {@link TestingCoE.Environment }
	 * 
	 */
	public void setEnvironment(TestingCoE.Environment value) {
		this.environment = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="TestDataFolderPath" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *         &lt;element name="TestResultsFolderPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="ScreenShotFolderPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="ScreenShotCapture" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="CapturePageTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="DebugMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="DataXmlFileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="SaveToXmlDataFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="Database">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="encrypted_password" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="connection_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "name", "url", "testDataFolderPath",
			"testResultsFolderPath", "screenShotFolderPath",
			"screenShotCapture", "capturePageTitle", "debugMode",
			"dataXmlFileName", "saveToXmlDataFile", "database" })
	public static class Environment {

		@XmlElement(name = "Name", required = true)
		protected String name;
		@XmlElement(name = "URL", required = true)
		protected String url;
		@XmlElement(name = "TestDataFolderPath", required = true)
		protected Object testDataFolderPath;
		@XmlElement(name = "TestResultsFolderPath", required = true)
		protected String testResultsFolderPath;
		@XmlElement(name = "ScreenShotFolderPath", required = true)
		protected String screenShotFolderPath;
		@XmlElement(name = "ScreenShotCapture", required = true)
		protected String screenShotCapture;
		@XmlElement(name = "CapturePageTitle", required = true)
		protected String capturePageTitle;
		@XmlElement(name = "DebugMode", required = true)
		protected String debugMode;
		@XmlElement(name = "DataXmlFileName", required = true)
		protected String dataXmlFileName;
		@XmlElement(name = "SaveToXmlDataFile", required = true)
		protected String saveToXmlDataFile;
		@XmlElement(name = "Database", required = true)
		protected TestingCoE.Environment.Database database;

		/**
		 * Gets the value of the name property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setName(String value) {
			this.name = value;
		}

		/**
		 * Gets the value of the url property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getURL() {
			return url;
		}

		/**
		 * Sets the value of the url property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setURL(String value) {
			this.url = value;
		}

		/**
		 * Gets the value of the testDataFolderPath property.
		 * 
		 * @return possible object is {@link Object }
		 * 
		 */
		public Object getTestDataFolderPath() {
			return testDataFolderPath;
		}

		/**
		 * Sets the value of the testDataFolderPath property.
		 * 
		 * @param value
		 *            allowed object is {@link Object }
		 * 
		 */
		public void setTestDataFolderPath(Object value) {
			this.testDataFolderPath = value;
		}

		/**
		 * Gets the value of the testResultsFolderPath property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getTestResultsFolderPath() {
			return testResultsFolderPath;
		}

		/**
		 * Sets the value of the testResultsFolderPath property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setTestResultsFolderPath(String value) {
			this.testResultsFolderPath = value;
		}

		/**
		 * Gets the value of the screenShotFolderPath property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getScreenShotFolderPath() {
			return screenShotFolderPath;
		}

		/**
		 * Sets the value of the screenShotFolderPath property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setScreenShotFolderPath(String value) {
			this.screenShotFolderPath = value;
		}

		/**
		 * Gets the value of the screenShotCapture property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getScreenShotCapture() {
			return screenShotCapture;
		}

		/**
		 * Sets the value of the screenShotCapture property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setScreenShotCapture(String value) {
			this.screenShotCapture = value;
		}

		/**
		 * Gets the value of the capturePageTitle property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCapturePageTitle() {
			return capturePageTitle;
		}

		/**
		 * Sets the value of the capturePageTitle property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCapturePageTitle(String value) {
			this.capturePageTitle = value;
		}

		/**
		 * Gets the value of the debugMode property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDebugMode() {
			return debugMode;
		}

		/**
		 * Sets the value of the debugMode property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setDebugMode(String value) {
			this.debugMode = value;
		}

		/**
		 * Gets the value of the dataXmlFileName property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDataXmlFileName() {
			return dataXmlFileName;
		}

		/**
		 * Sets the value of the dataXmlFileName property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setDataXmlFileName(String value) {
			this.dataXmlFileName = value;
		}

		/**
		 * Gets the value of the saveToXmlDataFile property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSaveToXmlDataFile() {
			return saveToXmlDataFile;
		}

		/**
		 * Sets the value of the saveToXmlDataFile property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSaveToXmlDataFile(String value) {
			this.saveToXmlDataFile = value;
		}

		/**
		 * Gets the value of the database property.
		 * 
		 * @return possible object is {@link TestingCoE.Environment.Database }
		 * 
		 */
		public TestingCoE.Environment.Database getDatabase() {
			return database;
		}

		/**
		 * Sets the value of the database property.
		 * 
		 * @param value
		 *            allowed object is {@link TestingCoE.Environment.Database }
		 * 
		 */
		public void setDatabase(TestingCoE.Environment.Database value) {
			this.database = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="encrypted_password" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="connection_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "username", "encryptedPassword",
				"connectionName" })
		public static class Database {

			@XmlElement(required = true)
			protected String username;
			@XmlElement(name = "encrypted_password", required = true)
			protected String encryptedPassword;
			@XmlElement(name = "connection_name", required = true)
			protected String connectionName;

			/**
			 * Gets the value of the username property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getUsername() {
				return username;
			}

			/**
			 * Sets the value of the username property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setUsername(String value) {
				this.username = value;
			}

			/**
			 * Gets the value of the encryptedPassword property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getEncryptedPassword() {
				return encryptedPassword;
			}

			/**
			 * Sets the value of the encryptedPassword property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setEncryptedPassword(String value) {
				this.encryptedPassword = value;
			}

			/**
			 * Gets the value of the connectionName property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getConnectionName() {
				return connectionName;
			}

			/**
			 * Sets the value of the connectionName property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setConnectionName(String value) {
				this.connectionName = value;
			}

		}

	}

}
